language: java

addons:
  apt:
    packages:
      - libxml2-utils
  chrome: stable
  sauce_connect: true

jdk:
- oraclejdk9
- openjdk11

# skip the Travis-CI install phase because Maven handles that directly
install:
- "true"

script:
- "google-chrome --version"
- "./mvnw -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pokta-tck install"
