language: java
jdk:
- oraclejdk8
install:
- "true"
script:
- "mvn install -Pokta-tck -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

addons:
  sauce_connect: true