okta:
  oauth2:
    redirectUri: /login/okta

security:
  oauth2:
    client:
      # Redirect to your local page and render the widget
      userAuthorizationUri: http://localhost:8080/login
#    sso:
#      loginPath: /authorization-code/callback